version: "3"
services:
  awscli:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=python:3.7-alpine
    container_name: awscli
    hostname: awscli
    image: icmdb/awscli
    environment:
#      - AWS_PROFILE=""
#      - AWS_DEFAULT_REGION=""
      - AWS_CONFIG_FILE="/root/.aws/config"
      - AWS_SHARED_CREDENTIALS_FILE="/root/.aws/credentials"
#      - AWS_ACCESS_KEY_ID=""
#      - AWS_SECRET_ACCESS_KEY="
    volumes:
      - ~/.aws:/root/.aws
#    command: bash -c "while(:;); do date; sleep 1; done"
